# -*- coding: utf-8 -*-
"""Lab 1 - Semana 1: Brief Introduction to Python and Jupyter Notebooks

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dTG5gc1OXKWVAivMqHRuaP_nJJBI0N2X
"""

#This is  a 'Code' Cell
print("This is  code cell")

# print statements
variable = "right in the strings!"
print(f"f strings allow you to embed variables {variable}")